In [1]:
import torch
import torch.nn as nn #It includes buildings blocks such as activation function and layer creation 

In [12]:
#input
torch.manual_seed(42)
inputs = torch.tensor([1.0, 2.0, 3.0]) #(x1, x2, x3)

In [13]:
neuron = nn.Linear(in_features=3, out_features=1) #linear activation function for weight calculation

In [14]:
output = neuron(inputs)

In [15]:
output

tensor([1.5244], grad_fn=<ViewBackward0>)

In [16]:
# verify using formula
#bias value initialize randomly so every time output will change without "torch.manual_seed(42)"
neuron.weight @ inputs + neuron.bias # @ --> for dot product

tensor([1.5244], grad_fn=<AddBackward0>)

In [17]:
# neuron.weight
neuron.bias

Parameter containing:
tensor([0.5304], requires_grad=True)